#!/usr/bin/env python

Import("env")

env_cgaltest = env.Clone()
 

env_cgaltest.Append(CPPPATH=["#thirdparty/cgal"]) 
env_cgaltest.Append(CPPPATH=["#thirdparty/eigen3"]) 
env_cgaltest.Append(CPPPATH=["#thirdparty/boost"]) 

env_cgaltest.add_source_files(env.modules_sources, "*.cpp")
