#!/usr/bin/env python

Import("env")

env_occtest = env.Clone()

if env["platform"] == "web":
    occ_include_path = "#thirdparty/occ770/wasm/inc"
    occ_lib_path = "#thirdparty/occ770/wasm/lib"
    env.Append(LIBPATH=[occ_lib_path])
elif env["platform"] == "windows":
    occ_include_path = "#thirdparty/occ770/mingw64/inc"
    occ_lib_path = "#thirdparty/occ770/mingw64/win64/vc14/lib"
    occ_lib_path_mscv = "#thirdparty/occ770/mingw64/win64/vc14/lib/winsows.editor"
    env.Append(LIBPATH=[occ_lib_path, occ_lib_path_mscv])

env_occtest.Append(CPPPATH=[occ_include_path])

# if env.msvc:
#     env_occtest.Append(LINKFLAGS=["TKernel.lib", "TKMath.lib", "TKTopAlgo.lib", "TKPrim.lib", "TKService.lib", "TKG3d.lib", "TKBRep.lib", "TKGeomAlgo.lib", "TKGeomBase.lib"])
# else:
env.Append(LIBS=["TKernel", "TKMath", "TKTopAlgo", "TKPrim", "TKService", "TKG3d", "TKBRep", "TKGeomAlgo", "TKGeomBase", "TKG2d", "TKMesh", "TKShHealing"])

env_occtest.add_source_files(env.modules_sources, "*.cpp")
